export enum CacheKeys {
  INFO_CONFIGS = 'info_configs',
  BANNER_LIST = 'banner_list',
  CHILD_LIST = 'child_list',
  CHILD_SCHEDULES = 'child_schedules',
  CHILD_INVITATIONS = 'child_invitations',
  PROFILE = 'profile',
  WIDGET_SETTINGS = 'widget_settings',
  UNREVIEWED_TRANSACTIONS = 'unreviewed_transactions',
  UNPAID_TRANSACTIONS = 'unpaid_transactions',
  EVENT_LIST = 'event_list',
  RECOMMENDED_ARTICLE_LIST = 'recommended_article_list',
  THREAD_LIST = 'thread_list',
  UNREAD_NOTIFICATION_COUNT = 'unread_notification_count',
}
